@host = https://localhost:7265

GET {{host}}/api/Machines
Accept: application/json

###

GET {{host}}/api/Machines/2
Accept: application/json

###

GET {{host}}/api/Machines/hot?minTemperature=30&maxTemperature=60
Accept: application/json

###

GET {{host}}/api/Machines/1/alarms
Accept: application/json

###

POST {{host}}/api/Machines
Content-Type: application/json

{
  "name": "CNC-01",
  "status": "Running",
  "temperature": 55
}

###

POST {{host}}/api/Machines/1/alarms
Content-Type: application/json

{
  "message": "Emergency stop"
}

###

PUT {{host}}/api/Machines/1
Content-Type: application/json

{
  "id": 1,
  "name": "Robot spawalniczy",
  "status": "Stopped",
  "temperature": 55
}

###

DELETE {{host}}/api/Machines/1
Content-Type: application/json
